name: Compile

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'DEBUG'
        type: boolean
        default: false
      force:
        description: 'force'
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Prepare
        env:
          CUSTOM: ${{ secrets.CUSTOM }}
        if: ${{ env.CUSTOM == '' }}
        run: exit 1
        
      - name: Custom
        env:
          DEBUG: ${{ vars.DEBUG || github.event.inputs.debug }}
          FORCE: ${{ github.event.inputs.force }}
        run: ${{ secrets.CUSTOM }}
